### PR TITLE
Need to rename test directory, too

### PR DESCRIPTION
**Pull request by andrewhao**
### Problem

The app prototype has a `test/app_prototype_web` directory that doesn't get renamed to the new snake-cased app name when cut.

### Solution

Rename it.

### CODE REVIEW

**Comment by andrewhao** [comment]
Bump - @craiglyons what do you think?

**Comment by craiglyons** [comment]
@andrewhao Thanks for the bump!
Will you please submit a new release along with the code PR?

**Comment by andrewhao** [comment]
@craiglyons Done!

**Comment by craiglyons** [comment]
✨ lgtm ✨ 
Thanks @andrewhao!  Merging.

**Pull request merged**
